### PR TITLE
Created Dockerfile, README.md modified to correspond

### PR DESCRIPTION
**Pull request by aahutsal**
I've created Dockerfile so it's possible to run server much simpler with Docker now.
@weex I'd suggest registering on http://hub.docker.com as `reinproject` and publishing built docker image there via:

```script
docker login // enter your credentials
docker push reinproject/causeway
```

Once done starting docker container will be as simple as 
```script
docker run -p 8332:8332 -p 2016:2016 --name reinproject-server reinproject/causeway
```
Without any need to `git clone` and `docker build`

### CODE REVIEW

**Comment by aahutsal** [comment]
Added .travis.yml. 
Looks like Travis build passes now

**Comment by weex** [comment]
Testing this now. Is there any way to autoinstall bitcoind and configure the same rpcuser and rpcpassword between it and causeway? I assume it's not too hard for someone to add bitcoind themselves once the docker container is running.

**Comment by weex** [comment]
My other question is what's the best way to view the logs or prints coming from cserver.py? Also for a paid server, we have a script monitor.py that needs to be run which monitors for incoming payments. I'm still trying to figure out if the docker way is useful at all for development or is really focused on production instances.

**Comment by aahutsal** [comment]
I'd suggest to create `docker-compose.yml` It will let to automatically download and start all additional containers running (e.g. bitcoind, postgresql).

Docker container may be running in `attached` mode `docker -ti run <image>`, or `docker start <container>` and then `docker attach <container>`

All is possible, basically.

**Comment by weex** [comment]
Interesting. If we should make a `docker-compose.yml` to enable a server to setup with bitcoind, postgresql preferably with them linked via securely generated passwords, then please create an issue for that. I'm more interested in economically sustainable, long-running nodes than making them really easy to spin up but making decentralization easier is a definite goal. p2p network architecture will no doubt evolve into something more sensible than the client directly connecting to each server.

**Comment by aahutsal** [comment]
Nope, docker containers linking is already secured enough to be running on single machine. You can bring `docker-compose.yml` to any docker-enabled service and it will automatically download, build and deploy stuff for you ;)
As you remember I proposed to start with Heroku. We had to get rid of `sqlite3` and put `postgresql` into it. Later I can try to run dokerized build on Heroku, as postgres is already there.

**Pull request merged**
