### PR TITLE
better docker-compose integration

### PR DESCRIPTION
**Pull request by aahutsal**
@weex please test it yourself. I'm not python developer, so don't know how importing needed variables from `settings.py` you should override DATABASE_URI from environment.
`postgresql` database is now used by default. Next step make it possible to configure postgresql, sqlite3 or other engine.

### CODE REVIEW

**Comment by weex** [comment]
Just got a chance to look at this and I see a lot of new docker related files in the root dir. Can you minimize how many are at root by moving most into a sub-directory?

**Comment by weex** [comment]
Hey Arsen, I'm happy to merge this if either you can move most of the files or let me know a reason why they can't or shouldn't be moved.

**Comment by aahutsal** [comment]
Sure, I can move into subdir but this is a good practice for ANY project to keep them in top. 

Reasons:
a) it's a good practice to have Dockerfile written the way that it starts building underlaying project using paths, related to project root directory. 
b) Single docker container could be quickly built with `docker build`
c) All compose could be built, deps downloaded and installed and up with simple `docker-compose up`

**Comment by weex** [comment]
Thanks Arsen

**Pull request merged**
